### ISSUE TITLE
Node.Js API Running on Docker

### ISSUE THREAD

**Issue by GastonValdes** [pusher/pusher-http-node#122]
I have a Node.Js Api exposing several endpoints and methos to crud a MongoDB database. I also triggers pusher channel.
It works perfectly fine on my machine but when I put it inside a docker everything works ok but the pusher trigger never occurs, the console log shows no error, but the pusher console shows no requests, even the debug console on pusher shows me the request from the API running on the hw, but nothing happend when I run it inside Docker.
Is any special consideration I should have to run a node.js api inside docker?
Some comments
A curl to http://api.pusherapp.com/ inside docker works fine.
A ping to anywhere on internet from the docker replies ok.
The front end can call the dockerize api an the get, post and patch methods can crud on the mongodb without any issue.
The only thing that's not working are the pusher.trigger calls.

Thanks in advanced 

PS: The code of the API is here https://gitlab.com/tfg-gastonvaldes/node-api-mongo-home

**Comment by elverkilde** [comment]
hi @GastonValdes, perhaps it's related to TLS. Could you try curling with TLS instead, i.e. `curl -v https://api-mt1.pusher.com`.

Your Pusher instance is configured with `encrypted = true` and `cluster = mt1`, meaning the URL above should be what you are hitting. 

If HTTPS does not work, it is probably because you need to update the CA store on the container. You can then add something like this to your dockerfile:
```
RUN apk --no-cache add ca-certificates
```

You can also disable HTTPS by setting the `encrypted = false`, but you should probably only do that for testing/debugging.

Sorry for the late reply.
